package Vistas;

import DAO.RutaDAO;
import DTO.Ruta;
import javax.swing.JOptionPane;

public class ModuloRuta extends javax.swing.JFrame {

    public ModuloRuta() {
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setTitle("Modulo Ruta");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCostoBase = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDistancia = new javax.swing.JTextField();
        txtTiempoEstimado = new javax.swing.JTextField();
        cboAgenciaDestino = new javax.swing.JComboBox<>();
        cboAgenciaOrigen = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Módulo Ruta");
        jLabel5.setToolTipText("DNI");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, 20));

        txtCostoBase.setBackground(new java.awt.Color(68, 68, 68));
        txtCostoBase.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtCostoBase.setForeground(new java.awt.Color(255, 255, 255));
        txtCostoBase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCostoBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(118, 118, 118)));
        txtCostoBase.setMinimumSize(new java.awt.Dimension(1, 20));
        txtCostoBase.setPreferredSize(new java.awt.Dimension(100, 30));
        txtCostoBase.setSelectionColor(new java.awt.Color(204, 204, 204));
        txtCostoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoBaseActionPerformed(evt);
            }
        });
        jPanel1.add(txtCostoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 190, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Agencia de Origen: ");
        jLabel6.setToolTipText("DNI");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Agencia de Destino:");
        jLabel7.setToolTipText("DNI");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, 20));

        txtDescripcion.setBackground(new java.awt.Color(68, 68, 68));
        txtDescripcion.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(118, 118, 118)));
        txtDescripcion.setMinimumSize(new java.awt.Dimension(1, 20));
        txtDescripcion.setPreferredSize(new java.awt.Dimension(100, 30));
        txtDescripcion.setSelectionColor(new java.awt.Color(204, 204, 204));
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 190, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tiempo estimado (Hrs):");
        jLabel9.setToolTipText("DNI");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, 20));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Distancia (km):");
        jLabel12.setToolTipText("DNI");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 80, 20));

        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 90, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 630, 160));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Descripción:");
        jLabel13.setToolTipText("DNI");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ruta.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 30, 40));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Costo base:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        txtDistancia.setBackground(new java.awt.Color(68, 68, 68));
        txtDistancia.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtDistancia.setForeground(new java.awt.Color(255, 255, 255));
        txtDistancia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDistancia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(118, 118, 118)));
        txtDistancia.setMinimumSize(new java.awt.Dimension(1, 20));
        txtDistancia.setPreferredSize(new java.awt.Dimension(100, 30));
        txtDistancia.setSelectionColor(new java.awt.Color(204, 204, 204));
        txtDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistanciaActionPerformed(evt);
            }
        });
        jPanel1.add(txtDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 190, -1));

        txtTiempoEstimado.setBackground(new java.awt.Color(68, 68, 68));
        txtTiempoEstimado.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtTiempoEstimado.setForeground(new java.awt.Color(255, 255, 255));
        txtTiempoEstimado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTiempoEstimado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(118, 118, 118)));
        txtTiempoEstimado.setMinimumSize(new java.awt.Dimension(1, 20));
        txtTiempoEstimado.setPreferredSize(new java.awt.Dimension(100, 30));
        txtTiempoEstimado.setSelectionColor(new java.awt.Color(204, 204, 204));
        txtTiempoEstimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoEstimadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTiempoEstimado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 190, -1));

        cboAgenciaDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel1.add(cboAgenciaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 190, -1));

        cboAgenciaOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel1.add(cboAgenciaOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCostoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoBaseActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            String descripcion = txtDescripcion.getText();
            int idAgenciaOrigen = Integer.parseInt(cboAgenciaOrigen.getSelectedItem().toString());
            int idAgenciaDestino = Integer.parseInt(cboAgenciaDestino.getSelectedItem().toString());
            double distanciaKm = Double.parseDouble(txtDistancia.getText());
            double tiempoEstimadoHoras = Double.parseDouble(txtTiempoEstimado.getText());
            double costoBase = Double.parseDouble(txtCostoBase.getText());
            
            Ruta ruta = new Ruta(descripcion, idAgenciaOrigen, idAgenciaDestino, distanciaKm, tiempoEstimadoHoras, costoBase);
            RutaDAO dao = new RutaDAO();
            
            if(dao.registrarRuta(ruta)) {
                JOptionPane.showMessageDialog(this, "Registro correcto");
            } else {
                JOptionPane.showMessageDialog(null, "Error: ");
            }
            
            // descripcion, id_agencia_origen, id_agencia_destino, distancia_km, tiempo_estimado_horas, costo_base
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Error: "+e);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistanciaActionPerformed

    private void txtTiempoEstimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoEstimadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoEstimadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloRuta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboAgenciaDestino;
    private javax.swing.JComboBox<String> cboAgenciaOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCostoBase;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDistancia;
    private javax.swing.JTextField txtTiempoEstimado;
    // End of variables declaration//GEN-END:variables
}
