package Vistas;

import Controladores.*;
import DAO.RutaDAO;
import DTO.Agencia;
import DTO.ParadaRuta;
import DTO.Ruta;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ModuloRuta extends javax.swing.JFrame {
    
    private int idRutaActual = -1;
    private int IdParadaActual = -1;
    private boolean modoEdicion = false;
    private ControladorRuta controlador;
    private boolean recargarCboAgencia = false;
    private int cantidadParadas = 0;

    public ModuloRuta() {
        initComponents();
        this.setLocationRelativeTo(null);
        controlador = new ControladorRuta();
        cargarTablaRutas();
        recargarCboAgencia = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCostoBase = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabRutas = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDistancia = new javax.swing.JTextField();
        txtTiempoEstimado = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabParadas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cboAgencia = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnAgregarParada = new javax.swing.JButton();
        btnEliminarParada = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modulo Ruta");
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Módulo Ruta");
        jLabel5.setToolTipText("DNI");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 20));

        txtCostoBase.setBackground(new java.awt.Color(68, 68, 68));
        txtCostoBase.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtCostoBase.setForeground(new java.awt.Color(255, 255, 255));
        txtCostoBase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCostoBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(118, 118, 118)));
        txtCostoBase.setMinimumSize(new java.awt.Dimension(1, 20));
        txtCostoBase.setPreferredSize(new java.awt.Dimension(100, 30));
        txtCostoBase.setSelectionColor(new java.awt.Color(204, 204, 204));
        txtCostoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoBaseActionPerformed(evt);
            }
        });
        txtCostoBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostoBaseKeyTyped(evt);
            }
        });
        jPanel1.add(txtCostoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 140, -1));

        txtDescripcion.setBackground(new java.awt.Color(68, 68, 68));
        txtDescripcion.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(118, 118, 118)));
        txtDescripcion.setMinimumSize(new java.awt.Dimension(1, 20));
        txtDescripcion.setPreferredSize(new java.awt.Dimension(100, 30));
        txtDescripcion.setSelectionColor(new java.awt.Color(204, 204, 204));
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 310, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tiempo estimado (Hrs):");
        jLabel9.setToolTipText("DNI");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, 20));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Distancia (km):");
        jLabel12.setToolTipText("DNI");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 80, 20));

        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 90, 30));

        tabRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Ruta", "Descripción", "Costo base", "Tiempo estimado (Hrs)", "Distancia(km)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabRutas.setColumnSelectionAllowed(true);
        tabRutas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabRutas);
        tabRutas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabRutas.getColumnModel().getColumnCount() > 0) {
            tabRutas.getColumnModel().getColumn(0).setPreferredWidth(1);
            tabRutas.getColumnModel().getColumn(2).setPreferredWidth(2);
            tabRutas.getColumnModel().getColumn(3).setPreferredWidth(2);
            tabRutas.getColumnModel().getColumn(4).setPreferredWidth(2);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 530, 200));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Descripción:");
        jLabel13.setToolTipText("DNI");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ruta.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 30, 40));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Costo base:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        txtDistancia.setBackground(new java.awt.Color(68, 68, 68));
        txtDistancia.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtDistancia.setForeground(new java.awt.Color(255, 255, 255));
        txtDistancia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDistancia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(118, 118, 118)));
        txtDistancia.setMinimumSize(new java.awt.Dimension(1, 20));
        txtDistancia.setPreferredSize(new java.awt.Dimension(100, 30));
        txtDistancia.setSelectionColor(new java.awt.Color(204, 204, 204));
        txtDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistanciaActionPerformed(evt);
            }
        });
        txtDistancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDistanciaKeyTyped(evt);
            }
        });
        jPanel1.add(txtDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 140, -1));

        txtTiempoEstimado.setBackground(new java.awt.Color(68, 68, 68));
        txtTiempoEstimado.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtTiempoEstimado.setForeground(new java.awt.Color(255, 255, 255));
        txtTiempoEstimado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTiempoEstimado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(118, 118, 118)));
        txtTiempoEstimado.setMinimumSize(new java.awt.Dimension(1, 20));
        txtTiempoEstimado.setPreferredSize(new java.awt.Dimension(100, 30));
        txtTiempoEstimado.setSelectionColor(new java.awt.Color(204, 204, 204));
        txtTiempoEstimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoEstimadoActionPerformed(evt);
            }
        });
        txtTiempoEstimado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTiempoEstimadoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTiempoEstimado, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 140, -1));

        tabParadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orden", "Agencia", "idAgencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabParadas.setColumnSelectionAllowed(true);
        tabParadas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabParadas);
        tabParadas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabParadas.getColumnModel().getColumnCount() > 0) {
            tabParadas.getColumnModel().getColumn(0).setPreferredWidth(1);
            tabParadas.getColumnModel().getColumn(2).setPreferredWidth(1);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 290, 320));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Paradas:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        cboAgencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        cboAgencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboAgenciaFocusGained(evt);
            }
        });
        cboAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAgenciaActionPerformed(evt);
            }
        });
        jPanel1.add(cboAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 240, 30));

        btnCancelar.setText("Cancelar");
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 90, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seleccionar Agencia:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        btnAgregarParada.setText("Agregar parada");
        btnAgregarParada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarParadaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarParada, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 120, 30));

        btnEliminarParada.setText("Eliminar parada");
        jPanel1.add(btnEliminarParada, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 120, 30));

        btnEditar.setText("Editar");
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 90, 30));

        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCostoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoBaseActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            //VALIDACION DE CAMPOS VACÍOS
            if (txtDescripcion.getText().trim().isEmpty()|| txtDistancia.getText().trim().isEmpty()
                    || txtTiempoEstimado.getText().trim().isEmpty()
                    || txtCostoBase.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this,
                        "Todos los campos deben estar llenos.","Campos vacíos",JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // --- VALIDAR QUE LOS NUMÉRICOS SEAN CORRECTOS ---
            double distanciaKm = Double.parseDouble(txtDistancia.getText());
            double tiempoEstimadoHoras = Double.parseDouble(txtTiempoEstimado.getText());
            double costoBase = Double.parseDouble(txtCostoBase.getText());
            String descripcion = txtDescripcion.getText();
            
            DefaultTableModel modelo = (DefaultTableModel) tabParadas.getModel();
            List<ParadaRuta> paradas = new ArrayList<>();
            
            // int idRuta, int idAgencia, int orden, String nombreAgencia
            
            for (int i = 0; i < modelo.getRowCount(); i++) {
                int orden = (int) modelo.getValueAt(i, 0);
                String nombreAgencia = (String) modelo.getValueAt(i, 1);
                int idAgencia = (int) modelo.getValueAt(i, 2);
                
                ParadaRuta parada = new ParadaRuta();
                parada.setOrden(orden);
                parada.setNombreAgencia(nombreAgencia);
                parada.setIdAgencia(idAgencia);
                
                paradas.add(parada);
            }

            Ruta ruta = new Ruta(
                    descripcion,
                    costoBase,
                    tiempoEstimadoHoras,
                    distanciaKm,
                    paradas
            );

            try {
                distanciaKm = Double.parseDouble(txtDistancia.getText());
                tiempoEstimadoHoras = Double.parseDouble(txtTiempoEstimado.getText());
                costoBase = Double.parseDouble(txtCostoBase.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "Los campos de distancia, tiempo y costo deben ser numéricos.",
                        "Formato incorrecto",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            // VALIDAR QUE LOS NUMÉRICOS SEAN POSITIVOS
            if (distanciaKm <= 0 || tiempoEstimadoHoras <= 0 || costoBase <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Los valores de distancia, tiempo y costo deben ser mayores que 0.",
                        "Valor inválido",JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            if (controlador.registrarRuta(ruta, paradas)) {
                JOptionPane.showMessageDialog(this, "Registro correcto");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar la ruta.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistanciaActionPerformed

    private void txtTiempoEstimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoEstimadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoEstimadoActionPerformed

    private void txtDistanciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDistanciaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txtDistanciaKeyTyped

    private void txtTiempoEstimadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiempoEstimadoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txtTiempoEstimadoKeyTyped

    private void txtCostoBaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoBaseKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCostoBaseKeyTyped

    private void cboAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboAgenciaActionPerformed

    // Cargar las Agencias al darle click por primera vez al combobox
    private void cboAgenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboAgenciaFocusGained
        if (!recargarCboAgencia) {
            return;
        }
        List<Agencia> agencias = controlador.obtenerAgencias();
        llenarCboAgencias(agencias);
        // Desactivar la recarga de agencias;
        recargarCboAgencia = false;
    }//GEN-LAST:event_cboAgenciaFocusGained

    private void btnAgregarParadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarParadaActionPerformed
        if(!modoEdicion) {
            DefaultTableModel modelo = (DefaultTableModel) tabParadas.getModel();
            Agencia agenciaSeleccionada = (Agencia) cboAgencia.getSelectedItem();
            cantidadParadas++;
            modelo.addRow(new Object[]{
                cantidadParadas,
                agenciaSeleccionada.getNombre(),
                agenciaSeleccionada.getIdAgencia()}
            );
        }
    }//GEN-LAST:event_btnAgregarParadaActionPerformed

    private void llenarCboAgencias(List<Agencia> agencias) {
        if(agencias != null) {
            for(Agencia a : agencias) {
                cboAgencia.addItem(a);
            }
        }
    }
    
    public void cargarTablaRutas() {
        //
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloRuta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarParada;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarParada;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Object> cboAgencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabParadas;
    private javax.swing.JTable tabRutas;
    private javax.swing.JTextField txtCostoBase;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDistancia;
    private javax.swing.JTextField txtTiempoEstimado;
    // End of variables declaration//GEN-END:variables
}
